### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by xavierzwirtz** [xtruder/kubenix#17]
I think I am seeing flakiness with the kube node getting spun up during test runs. I don't know enough to give more information, the output of `nix build -f ./. test-script` rapidly flashes incomplete information. It looks like its repeatedly running `("kubectl get node kube.my.xzy | grep -w Ready")`. Any guidance to getting more info on this?

**Comment by xavierzwirtz** [comment]
I can reproduce this with the nginx-deployment example. Steps to repro:

```
git clone https://github.com/xtruder/kubenix/
cd kubenix/examples/nginx-deployment
#run this command till failure, success happens quickly, failure takes 900 seconds before timeout
rm -f result && nix-collect-garbage -d && nix-build . -A test-script
```

**Comment by xavierzwirtz** [comment]
[hung output 1](https://gist.github.com/xavierzwirtz/04c47d8e89efea05265ba7d71e4e0dec)
[hung output 2](https://gist.github.com/xavierzwirtz/c9494c3eb4960cceafeee25f02d9ce6d)
[successful output](https://gist.github.com/xavierzwirtz/8ad3ff131ec390c4270cbca002526b5f)

**Comment by offlinehacker** [comment]
Thank you for reporting issue.  There are issues with e2e tests as kubetnetes module in nixos is having issues. I am planning to replace testing infra with k3s (or probably make different test profiles so you can choose how to run tests), which would also much shorten test time and resources used. If you can debug what is causing issues pull requests are much appreciated.

**Comment by offlinehacker** [comment]
There seems to be permission issues:

```
Failed to list *v1.Node: nodes is forbidden: User "system:kube-scheduler" cannot list resource "nodes" in API group "" at the cluster scope
```

**Comment by xavierzwirtz** [comment]
Thanks for taking a look. I didn't realize the tests themselves were flaky at first, was making minor changes to one of my tests and watching them hang. Thought I was going crazy.

Using k3s sounds lovely, faster test times would be great. Ill see if I can figure out whats going on with the existing tests, I want to move forward using kubenix.

**Comment by offlinehacker** [comment]
Yes, it would be also nice to have backend independent testing abstraction, so you can also run it on local kubernetes outside nix build process, using `nix-shell` or `nix run` on any k8s cluster. If you have any ideas how to implement/integrate something like this, it would be nice to discuss.

**Comment by offlinehacker** [comment]
This repo has been deprecated, since I stopped maintaining it some time ago. There is a fork maintained by @hall available at https://github.com/hall/kubenix, that has better documentation and looks like a way further.
