### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by zimbatm** [xtruder/kubenix#8]
hi @xtruder

kubenix is brilliant, it makes writing kubernetes resources so much more pleasant than helm.

Follows, a dump of my experience with the library:

## No derivation

It would be nice if the output was just a nix object. With `nix-instanciate --eval --strict --json` it should be possible to generate the same output but also not have anything written in the `/nix/store`. This is important when generating secret resources for example since the store is world-readable.

Fixed by https://github.com/xtruder/kubenix/pull/7

## Resource names and pluralization

It took me a while to figure out that resources are defined automatically from the swagger spec. Ingres is under "ingresses" and "PersistentVolume" is under "persistentVolumes".

## Not a lot of docs

I had to dig quite a bit to figure out how everything comes together. For example there is an option to choose the kubernetes schema under `config.kubernetes.version = "1.11"` and which default is "1.9".

If I hadn't been super comfortable with the nix language I would have probably given up.

TODO: submit PR to improve the doc

**Comment by domenkozar** [comment]
@offlinehacker :-)

**Comment by offlinehacker** [comment]
Thanks for the feedback, i completely agree with all ideas :smiley: 

Just to let you know, `kubenix` is in a progress of major refactoring, that will implement all ideas and fix all issues we had at @gatehubnet and make it generally available. I will also take into account all the ideas here. **Details and progress are in this issue:** https://github.com/xtruder/kubenix/issues/9

Let's finally finish this :muscle:

**Comment by offlinehacker** [comment]
Oh and thanks for finding `kubenix` usefull, i'm happy that also other people find similar issues with helm :smiley:

**Comment by offlinehacker** [comment]
This repo has been deprecated, since I stopped maintaining it some time ago. There is a fork maintained by @hall available at https://github.com/hall/kubenix, that has better documentation and looks like a way further.
